<a href="https://colab.research.google.com/github/maanaav15369/deep-learning-projects/blob/main/KERAS_HYPERPARAMETER_TUNING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('diabetes.csv')

In [3]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [5]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [6]:
x =df.iloc[:,:-1].values
y =df.iloc[:,-1].values

In [7]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [8]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

In [9]:
x

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [10]:
x.shape

(768, 8)

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [12]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [13]:
model = Sequential()
model.add(Dense(32,activation='relu',input_dim=8))
model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [15]:
model.fit(x_train,y_train,batch_size=32,epochs=100,validation_data=(x_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7769 - loss: 0.4915 - val_accuracy: 0.8117 - val_loss: 0.4631
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4847 - val_accuracy: 0.8117 - val_loss: 0.4571
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4792 - val_accuracy: 0.8052 - val_loss: 0.4525
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4743 - val_accuracy: 0.8052 - val_loss: 0.4494
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4709 - val_accuracy: 0.8052 - val_loss: 0.4461
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4677 - val_accuracy: 0.8052 - val_loss: 0.4440
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4648 - val_accuracy: 0.8052 - val_loss: 0.4433
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4625 - val_accuracy: 0.7987 - val_loss: 0.4426
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4605 - val_accuracy: 0.7922 - val_loss: 0.4418
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4595 - val_accuracy: 0.7792 - val_loss: 0.4426
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4570 - val_accuracy: 0.7857 - val_loss: 0.4414
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4553 - val_accuracy: 0.8052 - val_loss: 0.4395
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4544 - val_accuracy: 0.8117 - val_loss: 0.4384
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7801 - loss: 0.4530 - val_accuracy: 0.8117 - val_loss: 0.4376
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4524 - val_accuracy: 0.7922 - val_loss: 0.4397
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4508 - val_accuracy: 0.8052 - val_loss: 0.4401
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4497 - val_accuracy: 0.8117 - val_loss: 0.4393
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4486 - val_accuracy: 0.8117 - val_loss: 0.4390
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4482 - val_accuracy: 0.7922 - val_loss: 0.4393
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4472 - val_accuracy: 0.7987 - val_loss: 0.4396
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4465 - val_accuracy: 0.7922 - val_loss: 0.4390
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4454 - val_accuracy: 0.8117 - val_loss: 0.4384
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4448 - val_accuracy: 0.8117 - val_loss: 0.4388
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4445 - val_accuracy: 0.8052 - val_loss: 0.4391
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4437 - val_accuracy: 0.8052 - val_loss: 0.4384
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4433 - val_accuracy: 0.7987 - val_loss: 0.4387
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4427 - val_accuracy: 0.8052 - val_loss: 0.4385
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4425 - val_accuracy: 0.8052 - val_loss: 0.4392
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4421 - val_accuracy: 0.8052 - val_loss: 0.4394
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4416 - val_accuracy: 0.8117 - val_loss: 0.4384
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4414 - val_accuracy: 0.8052 - val_loss: 0.4409
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4407 - val_accuracy: 0.8182 - val_loss: 0.4412
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4405 - val_accuracy: 0.8182 - val_loss: 0.4400
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4402 - val_accuracy: 0.8182 - val_loss: 0.4405
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4394 - val_accuracy: 0.8182 - val_loss: 0.4402
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4393 - val_accuracy: 0.8117 - val_loss: 0.4388
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4389 - val_accuracy: 0.8247 - val_loss: 0.4380
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4384 - val_accuracy: 0.8182 - val_loss: 0.4385
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4378 - val_accuracy: 0.8247 - val_loss: 0.4386
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4376 - val_accuracy: 0.8312 - val_loss: 0.4386
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4374 - val_accuracy: 0.8182 - val_loss: 0.4391
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4373 - val_accuracy: 0.8247 - val_loss: 0.4382
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4367 - val_accuracy: 0.8247 - val_loss: 0.4387
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4362 - val_accuracy: 0.8182 - val_loss: 0.4400
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4360 - val_accuracy: 0.8182 - val_loss: 0.4404
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4356 - val_accuracy: 0.8312 - val_loss: 0.4412
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4352 - val_accuracy: 0.8312 - val_loss: 0.4410
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4347 - val_accuracy: 0.8182 - val_loss: 0.4409
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4345 - val_accuracy: 0.8182 - val_loss: 0.4415
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4342 - val_accuracy: 0.8182 - val_loss: 0.4418
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4339 - val_accuracy: 0.8247 - val_loss: 0.4417
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4335 - val_accuracy: 0.8182 - val_loss: 0.4422
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4329 - val_accuracy: 0.8312 - val_loss: 0.4417
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4327 - val_accuracy: 0.8312 - val_loss: 0.4418
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4323 - val_accuracy: 0.8312 - val_loss: 0.4415
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4315 - val_accuracy: 0.8312 - val_loss: 0.4416
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4318 - val_accuracy: 0.8312 - val_loss: 0.4426
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4311 - val_accuracy: 0.8247 - val_loss: 0.4426
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4306 - val_accuracy: 0.8312 - val_loss: 0.4424
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4301 - val_accuracy: 0.8377 - val_loss: 0.4432
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4299 - val_accuracy: 0.8442 - val_loss: 0.4427
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4297 - val_accuracy: 0.8377 - val_loss: 0.4429
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4292 - val_accuracy: 0.8442 - val_loss: 0.4414
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4290 - val_accuracy: 0.8442 - val_loss: 0.4416
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4286 - val_accuracy: 0.8442 - val_loss: 0.4424
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7915 - loss: 0.4284 - val_accuracy: 0.8377 - val_loss: 0.4406
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7866 - loss: 0.4284 - val_accuracy: 0.8377 - val_loss: 0.4417
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4273 - val_accuracy: 0.8377 - val_loss: 0.4422
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7850 - loss: 0.4274 - val_accuracy: 0.8377 - val_loss: 0.4431
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7899 - loss: 0.4271 - val_accuracy: 0.8377 - val_loss: 0.4420
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7866 - loss: 0.4263 - val_accuracy: 0.8377 - val_loss: 0.4430
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4259 - val_accuracy: 0.8312 - val_loss: 0.4436
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7948 - loss: 0.4265 - val_accuracy: 0.8377 - val_loss: 0.4422
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7932 - loss: 0.4255 - val_accuracy: 0.8442 - val_loss: 0.4430
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4250 - val_accuracy: 0.8377 - val_loss: 0.4436
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4250 - val_accuracy: 0.8312 - val_loss: 0.4424
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4246 - val_accuracy: 0.8377 - val_loss: 0.4427
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4241 - val_accuracy: 0.8377 - val_loss: 0.4413
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4239 - val_accuracy: 0.8312 - val_loss: 0.4400
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4237 - val_accuracy: 0.8247 - val_loss: 0.4399
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.7932 - loss: 0.4234 - val_accuracy: 0.8247 - val_loss: 0.4418
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.7932 - loss: 0.4229 - val_accuracy: 0.8312 - val_loss: 0.4426
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7932 - loss: 0.4225 - val_accuracy: 0.8312 - val_loss: 0.4421
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4223 - val_accuracy: 0.8312 - val_loss: 0.4417
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4221 - val_accuracy: 0.8312 - val_loss: 0.4424
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4215 - val_accuracy: 0.8312 - val_loss: 0.4439
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4223 - val_accuracy: 0.8312 - val_loss: 0.4439
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4213 - val_accuracy: 0.8312 - val_loss: 0.4438
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4208 - val_accuracy: 0.8312 - val_loss: 0.4432
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4204 - val_accuracy: 0.8247 - val_loss: 0.4432
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4207 - val_accuracy: 0.8312 - val_loss: 0.4443
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4200 - val_accuracy: 0.8247 - val_loss: 0.4442
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4200 - val_accuracy: 0.8247 - val_loss: 0.4448
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4200 - val_accuracy: 0.8247 - val_loss: 0.4455
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4190 - val_accuracy: 0.8247 - val_loss: 0.4448
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4185 - val_accuracy: 0.8312 - val_loss: 0.4442
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4186 - val_accuracy: 0.8247 - val_loss: 0.4444
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4191 - val_accuracy: 0.8247 - val_loss: 0.4455
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4183 - val_accuracy: 0.8182 - val_loss: 0.4452
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4177 - val_accuracy: 0.8247 - val_loss: 0.4453

In [16]:
#automation using keras tuner
#1.how to select appropriate optimizer
#2.no. of nodes in layer
#3.how to select no.of layers
#4.All in one model

In [17]:
import keras_tuner as kt

ModuleNotFoundError: No module named 'keras_tuner'

In [21]:
pip install -U keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.81.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.1)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.6.17)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 5.0 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [22]:
import keras_tuner as kt

In [26]:
from flax.nnx import optimizer
def build_model(hp):

  model = Sequential()
  model.add(Dense(32,activation='relu',input_dim=8))
  model.add(Dense(1,activation='sigmoid'))

  optimizer = hp.Choice('optimizer',values=['adam','sgd','rmsprop','adadelta'])

  model.compile(optimizer=optimizer,loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [27]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=5)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [28]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Trial 4 Complete [00h 00m 02s]
val_accuracy: 0.7402597665786743

Best val_accuracy So Far: 0.7402597665786743
Total elapsed time: 00h 00m 11s

In [29]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [30]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [31]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [32]:
model.fit(x_train,y_train,batch_size=32,epochs=100,initial_epoch=6,validation_data=(x_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.7264 - loss: 0.5426 - val_accuracy: 0.7662 - val_loss: 0.5180
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7362 - loss: 0.5224 - val_accuracy: 0.7792 - val_loss: 0.5039
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7443 - loss: 0.5093 - val_accuracy: 0.7792 - val_loss: 0.4931
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7524 - loss: 0.4984 - val_accuracy: 0.7727 - val_loss: 0.4852
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.4903 - val_accuracy: 0.7792 - val_loss: 0.4794
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4838 - val_accuracy: 0.7792 - val_loss: 0.4748
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4785 - val_accuracy: 0.7792 - val_loss: 0.4710
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4743 - val_accuracy: 0.7857 - val_loss: 0.4680
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4705 - val_accuracy: 0.8052 - val_loss: 0.4670
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4674 - val_accuracy: 0.7922 - val_loss: 0.4664
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4649 - val_accuracy: 0.7922 - val_loss: 0.4668
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4626 - val_accuracy: 0.7922 - val_loss: 0.4657
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4608 - val_accuracy: 0.7857 - val_loss: 0.4657
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4594 - val_accuracy: 0.7857 - val_loss: 0.4646
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4575 - val_accuracy: 0.7857 - val_loss: 0.4646
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4564 - val_accuracy: 0.7857 - val_loss: 0.4640
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4554 - val_accuracy: 0.7857 - val_loss: 0.4643
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4544 - val_accuracy: 0.7857 - val_loss: 0.4650
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4528 - val_accuracy: 0.7922 - val_loss: 0.4658
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4527 - val_accuracy: 0.7857 - val_loss: 0.4655
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4516 - val_accuracy: 0.7857 - val_loss: 0.4646
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4507 - val_accuracy: 0.7792 - val_loss: 0.4652
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4500 - val_accuracy: 0.7857 - val_loss: 0.4645
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4491 - val_accuracy: 0.7857 - val_loss: 0.4645
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4483 - val_accuracy: 0.7922 - val_loss: 0.4639
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4473 - val_accuracy: 0.7922 - val_loss: 0.4638
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4467 - val_accuracy: 0.7857 - val_loss: 0.4625
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4461 - val_accuracy: 0.7792 - val_loss: 0.4624
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4459 - val_accuracy: 0.7922 - val_loss: 0.4619
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4448 - val_accuracy: 0.7922 - val_loss: 0.4619
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4445 - val_accuracy: 0.7922 - val_loss: 0.4627
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4435 - val_accuracy: 0.7922 - val_loss: 0.4628
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4431 - val_accuracy: 0.7922 - val_loss: 0.4633
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4422 - val_accuracy: 0.7922 - val_loss: 0.4629
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4417 - val_accuracy: 0.7987 - val_loss: 0.4635
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4411 - val_accuracy: 0.7922 - val_loss: 0.4652
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4405 - val_accuracy: 0.7922 - val_loss: 0.4641
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4400 - val_accuracy: 0.7987 - val_loss: 0.4638
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4395 - val_accuracy: 0.7922 - val_loss: 0.4651
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4390 - val_accuracy: 0.7987 - val_loss: 0.4646
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4386 - val_accuracy: 0.7987 - val_loss: 0.4647
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4383 - val_accuracy: 0.7987 - val_loss: 0.4644
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4375 - val_accuracy: 0.7922 - val_loss: 0.4646
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7883 - loss: 0.4368 - val_accuracy: 0.7922 - val_loss: 0.4641
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.7883 - loss: 0.4368 - val_accuracy: 0.7922 - val_loss: 0.4637
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4366 - val_accuracy: 0.7987 - val_loss: 0.4642
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4354 - val_accuracy: 0.7987 - val_loss: 0.4635
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4352 - val_accuracy: 0.7987 - val_loss: 0.4637
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4347 - val_accuracy: 0.7987 - val_loss: 0.4628
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4341 - val_accuracy: 0.7987 - val_loss: 0.4633
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4337 - val_accuracy: 0.7987 - val_loss: 0.4634
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4335 - val_accuracy: 0.7987 - val_loss: 0.4635
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4329 - val_accuracy: 0.7987 - val_loss: 0.4631
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4331 - val_accuracy: 0.7987 - val_loss: 0.4626
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4322 - val_accuracy: 0.7922 - val_loss: 0.4620
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4321 - val_accuracy: 0.7987 - val_loss: 0.4623
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4313 - val_accuracy: 0.7987 - val_loss: 0.4618
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4312 - val_accuracy: 0.7922 - val_loss: 0.4621
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4308 - val_accuracy: 0.7922 - val_loss: 0.4625
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4299 - val_accuracy: 0.7987 - val_loss: 0.4626
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4298 - val_accuracy: 0.7922 - val_loss: 0.4623
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4296 - val_accuracy: 0.7987 - val_loss: 0.4620
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4288 - val_accuracy: 0.7987 - val_loss: 0.4614
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4286 - val_accuracy: 0.7987 - val_loss: 0.4616
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4285 - val_accuracy: 0.8052 - val_loss: 0.4624
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4279 - val_accuracy: 0.7987 - val_loss: 0.4624
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4276 - val_accuracy: 0.7987 - val_loss: 0.4621
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4272 - val_accuracy: 0.7987 - val_loss: 0.4622
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4270 - val_accuracy: 0.7987 - val_loss: 0.4625
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4265 - val_accuracy: 0.7987 - val_loss: 0.4612
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4265 - val_accuracy: 0.8052 - val_loss: 0.4610
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4258 - val_accuracy: 0.8117 - val_loss: 0.4601
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7883 - loss: 0.4255 - val_accuracy: 0.8052 - val_loss: 0.4604
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4252 - val_accuracy: 0.8052 - val_loss: 0.4604
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7964 - loss: 0.4245 - val_accuracy: 0.7987 - val_loss: 0.4605
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4247 - val_accuracy: 0.8052 - val_loss: 0.4598
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4236 - val_accuracy: 0.8052 - val_loss: 0.4594
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4236 - val_accuracy: 0.8052 - val_loss: 0.4607
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7948 - loss: 0.4233 - val_accuracy: 0.7987 - val_loss: 0.4619
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4228 - val_accuracy: 0.8052 - val_loss: 0.4615
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4225 - val_accuracy: 0.8052 - val_loss: 0.4614
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4223 - val_accuracy: 0.8117 - val_loss: 0.4609
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4221 - val_accuracy: 0.8052 - val_loss: 0.4595
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4215 - val_accuracy: 0.8117 - val_loss: 0.4599
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4216 - val_accuracy: 0.8117 - val_loss: 0.4589
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4210 - val_accuracy: 0.7987 - val_loss: 0.4577
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4207 - val_accuracy: 0.7987 - val_loss: 0.4578
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4206 - val_accuracy: 0.7987 - val_loss: 0.4579
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4199 - val_accuracy: 0.7987 - val_loss: 0.4575
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4199 - val_accuracy: 0.7987 - val_loss: 0.4573
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4192 - val_accuracy: 0.8117 - val_loss: 0.4577
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4193 - val_accuracy: 0.8117 - val_loss: 0.4578
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4189 - val_accuracy: 0.7987 - val_loss: 0.4584
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4190 - val_accuracy: 0.7987 - val_loss: 0.4593

In [41]:
#hyperparameter tuning for right number of nuerons
def build_model(hp):

  model = Sequential()

  units = hp.Int('units', min_value=8, max_value=128, step=8)

  model.add(Dense(units=units,activation='relu',input_dim=8))
  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])

  return model

In [50]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=5,
                        directory='mydir',
                        project_name='test project')

Reloading Tuner from mydir/test project/tuner0.json

In [43]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Trial 5 Complete [00h 00m 02s]
val_accuracy: 0.8051947951316833

Best val_accuracy So Far: 0.8181818127632141
Total elapsed time: 00h 00m 14s

In [44]:
tuner.get_best_hyperparameters()[0].values

{'units': 88}

In [45]:
model =tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [47]:
model.fit(x_train,y_train,batch_size=32,epochs=100,initial_epoch=6,validation_data=(x_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.7622 - loss: 0.5005 - val_accuracy: 0.8182 - val_loss: 0.4829
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4831 - val_accuracy: 0.8052 - val_loss: 0.4773
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7818 - loss: 0.4737 - val_accuracy: 0.8052 - val_loss: 0.4733
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7736 - loss: 0.4681 - val_accuracy: 0.8052 - val_loss: 0.4696
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7687 - loss: 0.4638 - val_accuracy: 0.7922 - val_loss: 0.4680
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7720 - loss: 0.4607 - val_accuracy: 0.7922 - val_loss: 0.4668
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7752 - loss: 0.4570 - val_accuracy: 0.7922 - val_loss: 0.4669
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7720 - loss: 0.4555 - val_accuracy: 0.8052 - val_loss: 0.4674
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7752 - loss: 0.4531 - val_accuracy: 0.8052 - val_loss: 0.4682
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7785 - loss: 0.4513 - val_accuracy: 0.8052 - val_loss: 0.4664
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7785 - loss: 0.4499 - val_accuracy: 0.8052 - val_loss: 0.4661
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7785 - loss: 0.4484 - val_accuracy: 0.8052 - val_loss: 0.4650
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4475 - val_accuracy: 0.7922 - val_loss: 0.4631
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4457 - val_accuracy: 0.7987 - val_loss: 0.4630
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4453 - val_accuracy: 0.7987 - val_loss: 0.4617
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4440 - val_accuracy: 0.8117 - val_loss: 0.4643
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4431 - val_accuracy: 0.8117 - val_loss: 0.4642
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4421 - val_accuracy: 0.8117 - val_loss: 0.4625
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4419 - val_accuracy: 0.8052 - val_loss: 0.4618
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4402 - val_accuracy: 0.7987 - val_loss: 0.4618
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4398 - val_accuracy: 0.7987 - val_loss: 0.4603
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4387 - val_accuracy: 0.7987 - val_loss: 0.4611
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4377 - val_accuracy: 0.8117 - val_loss: 0.4621
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4370 - val_accuracy: 0.8052 - val_loss: 0.4624
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4364 - val_accuracy: 0.7987 - val_loss: 0.4595
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4354 - val_accuracy: 0.8117 - val_loss: 0.4575
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4348 - val_accuracy: 0.8052 - val_loss: 0.4583
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4338 - val_accuracy: 0.8117 - val_loss: 0.4595
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4336 - val_accuracy: 0.8117 - val_loss: 0.4599
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4320 - val_accuracy: 0.8117 - val_loss: 0.4587
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7850 - loss: 0.4316 - val_accuracy: 0.8117 - val_loss: 0.4584
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4307 - val_accuracy: 0.8117 - val_loss: 0.4599
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7850 - loss: 0.4304 - val_accuracy: 0.8117 - val_loss: 0.4596
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7866 - loss: 0.4296 - val_accuracy: 0.8117 - val_loss: 0.4581
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4293 - val_accuracy: 0.8052 - val_loss: 0.4588
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4289 - val_accuracy: 0.8117 - val_loss: 0.4588
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4277 - val_accuracy: 0.8182 - val_loss: 0.4580
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4271 - val_accuracy: 0.8182 - val_loss: 0.4589
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4265 - val_accuracy: 0.8247 - val_loss: 0.4572
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4257 - val_accuracy: 0.8247 - val_loss: 0.4567
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4251 - val_accuracy: 0.8247 - val_loss: 0.4558
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4251 - val_accuracy: 0.8247 - val_loss: 0.4554
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4240 - val_accuracy: 0.8247 - val_loss: 0.4569
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4229 - val_accuracy: 0.8182 - val_loss: 0.4580
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4229 - val_accuracy: 0.8247 - val_loss: 0.4557
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4224 - val_accuracy: 0.8182 - val_loss: 0.4556
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4207 - val_accuracy: 0.8182 - val_loss: 0.4545
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4208 - val_accuracy: 0.8247 - val_loss: 0.4545
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4204 - val_accuracy: 0.8247 - val_loss: 0.4522
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4199 - val_accuracy: 0.8247 - val_loss: 0.4520
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4191 - val_accuracy: 0.8247 - val_loss: 0.4539
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4185 - val_accuracy: 0.8182 - val_loss: 0.4547
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4185 - val_accuracy: 0.8182 - val_loss: 0.4552
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4181 - val_accuracy: 0.8247 - val_loss: 0.4551
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4162 - val_accuracy: 0.8247 - val_loss: 0.4561
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4165 - val_accuracy: 0.8247 - val_loss: 0.4556
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4157 - val_accuracy: 0.8247 - val_loss: 0.4565
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4153 - val_accuracy: 0.8247 - val_loss: 0.4553
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4148 - val_accuracy: 0.8117 - val_loss: 0.4535
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4142 - val_accuracy: 0.8247 - val_loss: 0.4538
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4131 - val_accuracy: 0.8117 - val_loss: 0.4557
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4129 - val_accuracy: 0.8247 - val_loss: 0.4548
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4126 - val_accuracy: 0.8182 - val_loss: 0.4561
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4111 - val_accuracy: 0.8312 - val_loss: 0.4565
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8078 - loss: 0.4111 - val_accuracy: 0.8247 - val_loss: 0.4556
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8094 - loss: 0.4105 - val_accuracy: 0.8312 - val_loss: 0.4572
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8094 - loss: 0.4098 - val_accuracy: 0.8182 - val_loss: 0.4537
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8192 - loss: 0.4097 - val_accuracy: 0.8182 - val_loss: 0.4526
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8094 - loss: 0.4086 - val_accuracy: 0.8247 - val_loss: 0.4533
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4086 - val_accuracy: 0.8182 - val_loss: 0.4532
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8143 - loss: 0.4077 - val_accuracy: 0.8182 - val_loss: 0.4555
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4073 - val_accuracy: 0.8182 - val_loss: 0.4530
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8094 - loss: 0.4066 - val_accuracy: 0.8182 - val_loss: 0.4531
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.4060 - val_accuracy: 0.8312 - val_loss: 0.4528
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.4058 - val_accuracy: 0.8247 - val_loss: 0.4551
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.4051 - val_accuracy: 0.8247 - val_loss: 0.4544
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.4042 - val_accuracy: 0.8312 - val_loss: 0.4558
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8225 - loss: 0.4044 - val_accuracy: 0.8247 - val_loss: 0.4554
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8192 - loss: 0.4034 - val_accuracy: 0.8247 - val_loss: 0.4564
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8160 - loss: 0.4034 - val_accuracy: 0.8247 - val_loss: 0.4570
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8176 - loss: 0.4030 - val_accuracy: 0.8117 - val_loss: 0.4573
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8225 - loss: 0.4024 - val_accuracy: 0.8312 - val_loss: 0.4567
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8192 - loss: 0.4015 - val_accuracy: 0.8247 - val_loss: 0.4550
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8208 - loss: 0.4016 - val_accuracy: 0.8247 - val_loss: 0.4563
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8241 - loss: 0.4008 - val_accuracy: 0.8247 - val_loss: 0.4565
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8274 - loss: 0.4008 - val_accuracy: 0.8247 - val_loss: 0.4559
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8290 - loss: 0.4001 - val_accuracy: 0.8117 - val_loss: 0.4559
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8257 - loss: 0.3984 - val_accuracy: 0.8247 - val_loss: 0.4564
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3990 - val_accuracy: 0.8182 - val_loss: 0.4550
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3990 - val_accuracy: 0.8312 - val_loss: 0.4583
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3973 - val_accuracy: 0.8182 - val_loss: 0.4614
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3982 - val_accuracy: 0.8247 - val_loss: 0.4596
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3974 - val_accuracy: 0.8247 - val_loss: 0.4592
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3969 - val_accuracy: 0.8182 - val_loss: 0.4590

In [51]:
#3
def build_model(hp):

  model = Sequential()

  model.add(Dense(72,activation='relu',input_dim=8))

  for i in range(hp.Int('num_layers',min_value=1,max_value=10)):

    model.add(Dense(72,activation='relu'))

  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])

  return model

In [52]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=5,
                        directory='mydir',
                        project_name='num_layers')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [53]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.8181818127632141

Best val_accuracy So Far: 0.8181818127632141
Total elapsed time: 00h 00m 17s

In [54]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 5}

In [58]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 16 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [60]:
model.fit(x_train,y_train,batch_size=32,epochs=100,initial_epoch=6,validation_data=(x_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - accuracy: 0.7769 - loss: 0.4795 - val_accuracy: 0.8117 - val_loss: 0.4731
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4493 - val_accuracy: 0.7727 - val_loss: 0.4844
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4338 - val_accuracy: 0.7338 - val_loss: 0.5588
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4398 - val_accuracy: 0.7857 - val_loss: 0.4656
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4167 - val_accuracy: 0.7597 - val_loss: 0.4910
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4123 - val_accuracy: 0.7727 - val_loss: 0.4973
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8290 - loss: 0.4022 - val_accuracy: 0.7727 - val_loss: 0.4824
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3936 - val_accuracy: 0.7987 - val_loss: 0.4898
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3802 - val_accuracy: 0.7792 - val_loss: 0.4914
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3818 - val_accuracy: 0.8052 - val_loss: 0.4936
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3705 - val_accuracy: 0.8117 - val_loss: 0.4771
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3601 - val_accuracy: 0.7662 - val_loss: 0.5094
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3432 - val_accuracy: 0.7792 - val_loss: 0.5184
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8469 - loss: 0.3411 - val_accuracy: 0.8117 - val_loss: 0.4927
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8632 - loss: 0.3243 - val_accuracy: 0.7792 - val_loss: 0.5037
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8664 - loss: 0.3204 - val_accuracy: 0.7468 - val_loss: 0.6342
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8844 - loss: 0.2976 - val_accuracy: 0.7922 - val_loss: 0.5494
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8795 - loss: 0.2981 - val_accuracy: 0.7792 - val_loss: 0.5798
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8811 - loss: 0.2747 - val_accuracy: 0.7792 - val_loss: 0.5801
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9055 - loss: 0.2654 - val_accuracy: 0.7208 - val_loss: 0.7910
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8941 - loss: 0.2671 - val_accuracy: 0.7532 - val_loss: 0.6047
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9153 - loss: 0.2362 - val_accuracy: 0.7597 - val_loss: 0.6804
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9218 - loss: 0.2241 - val_accuracy: 0.7597 - val_loss: 0.6983
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9300 - loss: 0.2118 - val_accuracy: 0.7597 - val_loss: 0.7088
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9316 - loss: 0.2001 - val_accuracy: 0.7013 - val_loss: 1.1197
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9218 - loss: 0.2178 - val_accuracy: 0.7403 - val_loss: 0.7703
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9267 - loss: 0.1889 - val_accuracy: 0.7403 - val_loss: 0.9811
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9300 - loss: 0.1810 - val_accuracy: 0.7273 - val_loss: 0.9257
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9349 - loss: 0.1792 - val_accuracy: 0.7273 - val_loss: 1.0553
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9430 - loss: 0.1668 - val_accuracy: 0.7338 - val_loss: 0.8899
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9495 - loss: 0.1489 - val_accuracy: 0.7338 - val_loss: 0.9182
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9414 - loss: 0.1711 - val_accuracy: 0.7532 - val_loss: 0.9028
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9511 - loss: 0.1469 - val_accuracy: 0.7208 - val_loss: 1.0027
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9544 - loss: 0.1435 - val_accuracy: 0.7143 - val_loss: 0.9397
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9593 - loss: 0.1294 - val_accuracy: 0.7403 - val_loss: 1.0012
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9511 - loss: 0.1415 - val_accuracy: 0.7403 - val_loss: 1.0493
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9544 - loss: 0.1228 - val_accuracy: 0.6818 - val_loss: 1.0715
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9593 - loss: 0.1160 - val_accuracy: 0.7143 - val_loss: 1.1379
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9609 - loss: 0.1264 - val_accuracy: 0.7208 - val_loss: 1.1764
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9723 - loss: 0.0880 - val_accuracy: 0.7403 - val_loss: 1.2074
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9593 - loss: 0.1152 - val_accuracy: 0.7338 - val_loss: 1.3397
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9544 - loss: 0.1263 - val_accuracy: 0.7143 - val_loss: 1.1548
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9707 - loss: 0.0856 - val_accuracy: 0.7273 - val_loss: 1.2344
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9691 - loss: 0.0841 - val_accuracy: 0.6883 - val_loss: 1.3791
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9642 - loss: 0.0912 - val_accuracy: 0.7273 - val_loss: 1.4215
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9707 - loss: 0.0878 - val_accuracy: 0.7338 - val_loss: 1.4215
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9723 - loss: 0.0795 - val_accuracy: 0.7338 - val_loss: 1.3524
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9723 - loss: 0.0844 - val_accuracy: 0.7273 - val_loss: 1.3351
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9756 - loss: 0.0676 - val_accuracy: 0.7532 - val_loss: 1.4028
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9805 - loss: 0.0616 - val_accuracy: 0.7143 - val_loss: 1.7438
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9658 - loss: 0.0990 - val_accuracy: 0.7078 - val_loss: 1.3666
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9805 - loss: 0.0578 - val_accuracy: 0.7338 - val_loss: 1.4628
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9870 - loss: 0.0434 - val_accuracy: 0.7403 - val_loss: 1.4003
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9577 - loss: 0.1022 - val_accuracy: 0.6948 - val_loss: 1.4956
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9788 - loss: 0.0520 - val_accuracy: 0.6818 - val_loss: 1.7568
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9772 - loss: 0.0692 - val_accuracy: 0.7208 - val_loss: 1.8238
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0442 - val_accuracy: 0.7013 - val_loss: 1.6863
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9788 - loss: 0.0625 - val_accuracy: 0.7403 - val_loss: 1.5341
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0442 - val_accuracy: 0.7273 - val_loss: 1.7408
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0296 - val_accuracy: 0.6623 - val_loss: 1.8430
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9691 - loss: 0.0686 - val_accuracy: 0.6948 - val_loss: 1.6277
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9935 - loss: 0.0225 - val_accuracy: 0.6818 - val_loss: 2.2094
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9821 - loss: 0.0452 - val_accuracy: 0.7143 - val_loss: 1.8241
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0328 - val_accuracy: 0.7468 - val_loss: 1.8003
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0266 - val_accuracy: 0.7208 - val_loss: 2.0000
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9805 - loss: 0.0716 - val_accuracy: 0.7403 - val_loss: 1.7536
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0295 - val_accuracy: 0.7403 - val_loss: 1.8475
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0185 - val_accuracy: 0.7143 - val_loss: 2.0339
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9837 - loss: 0.0629 - val_accuracy: 0.7013 - val_loss: 2.2794
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9870 - loss: 0.0398 - val_accuracy: 0.7208 - val_loss: 1.9124
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0084 - val_accuracy: 0.7208 - val_loss: 2.0301
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0210 - val_accuracy: 0.7468 - val_loss: 2.0093
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9886 - loss: 0.0645 - val_accuracy: 0.7468 - val_loss: 1.9470
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0383 - val_accuracy: 0.7273 - val_loss: 1.8629
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0305 - val_accuracy: 0.7208 - val_loss: 2.0860
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0166 - val_accuracy: 0.7208 - val_loss: 2.4246
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0438 - val_accuracy: 0.7273 - val_loss: 2.0997
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0382 - val_accuracy: 0.7208 - val_loss: 2.0334
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0228 - val_accuracy: 0.7078 - val_loss: 2.0115
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0164 - val_accuracy: 0.7208 - val_loss: 2.2666
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9772 - loss: 0.0596 - val_accuracy: 0.7143 - val_loss: 2.1855
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9919 - loss: 0.0305 - val_accuracy: 0.7403 - val_loss: 2.0471
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0165 - val_accuracy: 0.7403 - val_loss: 2.2032
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0151 - val_accuracy: 0.7403 - val_loss: 2.3587
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0218 - val_accuracy: 0.7403 - val_loss: 2.1825
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0161 - val_accuracy: 0.7143 - val_loss: 2.0760
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0036 - val_accuracy: 0.7273 - val_loss: 2.4176
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0451 - val_accuracy: 0.7468 - val_loss: 2.5199
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0339 - val_accuracy: 0.7662 - val_loss: 2.0180
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0048 - val_accuracy: 0.7468 - val_loss: 2.2693
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0486 - val_accuracy: 0.7143 - val_loss: 2.2978
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0462 - val_accuracy: 0.7143 - val_loss: 2.2970
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0177 - val_accuracy: 0.7403 - val_loss: 2.1477
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.7403 - val_loss: 2.2639

In [67]:
#4
def build_model(hp):

  model = Sequential()

  counter = 0

  for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
    if counter == 0:
      model.add(
          Dense(
              hp.Int('units'+str(i),min_value=8,max_value=128,step=8),
              activation=hp.Choice('activation'+str(i),values=['relu','tanh','sigmoid']),
              input_dim=8
          )
      )
    else:
      model.add(
          Dense(
              hp.Int('units'+str(i),min_value=8,max_value=128,step=8),
              activation=hp.Choice('activation'+str(i),values=['relu','tanh','sigmoid'])
          )
      )
    counter+=1

  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer=hp.Choice('optimizer',values=['adam','sgd','rmsprop','adadelta','nadam']),
                        loss='binary_crossentropy',
                        metrics=['accuracy'])

  return model

In [69]:
tuner =kt.RandomSearch(build_model,
                       objective='val_accuracy',
                       max_trials=3,
                       directory="mydir",
                       project_name="final")

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [74]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 6,
 'units0': 40,
 'activation0': 'sigmoid',
 'optimizer': 'nadam',
 'units1': 8,
 'activation1': 'relu',
 'units2': 8,
 'activation2': 'relu',
 'units3': 8,
 'activation3': 'relu',
 'units4': 8,
 'activation4': 'relu',
 'units5': 8,
 'activation5': 'relu'}

In [75]:
model.fit(x_train,y_train,batch_size=32,epochs=200,initial_epoch=6,validation_data=(x_test,y_test))

Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.9967 - loss: 0.0151 - val_accuracy: 0.7532 - val_loss: 2.4460
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9951 - loss: 0.0086 - val_accuracy: 0.7143 - val_loss: 2.6011
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0454 - val_accuracy: 0.7597 - val_loss: 2.3457
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9772 - loss: 0.0425 - val_accuracy: 0.7208 - val_loss: 2.7389
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0341 - val_accuracy: 0.7338 - val_loss: 2.3700
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0164 - val_accuracy: 0.7078 - val_loss: 2.2780
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0154 - val_accuracy: 0.7468 - val_loss: 2.3339
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0180 - val_accuracy: 0.6883 - val_loss: 2.3751
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9870 - loss: 0.0432 - val_accuracy: 0.7078 - val_loss: 2.5437
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0034 - val_accuracy: 0.7403 - val_loss: 2.2541
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 6.5594e-04 - val_accuracy: 0.7338 - val_loss: 2.3617
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 4.1570e-04 - val_accuracy: 0.7078 - val_loss: 2.9574
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9805 - loss: 0.0776 - val_accuracy: 0.7208 - val_loss: 2.4750
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9967 - loss: 0.0141 - val_accuracy: 0.7208 - val_loss: 2.5126
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0010 - val_accuracy: 0.7013 - val_loss: 2.6716
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9886 - loss: 0.0268 - val_accuracy: 0.7597 - val_loss: 2.6934
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9805 - loss: 0.0659 - val_accuracy: 0.7403 - val_loss: 2.3780
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9984 - loss: 0.0022 - val_accuracy: 0.7273 - val_loss: 2.3613
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 4.0728e-04 - val_accuracy: 0.7273 - val_loss: 2.4148
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 3.6863e-04 - val_accuracy: 0.7468 - val_loss: 2.5548
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9967 - loss: 0.0148 - val_accuracy: 0.7597 - val_loss: 2.5696
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0339 - val_accuracy: 0.7338 - val_loss: 2.3152
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 6.0185e-04 - val_accuracy: 0.7468 - val_loss: 2.4175
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 2.5338e-04 - val_accuracy: 0.7403 - val_loss: 2.5099
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.5752e-04 - val_accuracy: 0.7273 - val_loss: 2.6755
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0752 - val_accuracy: 0.7468 - val_loss: 2.7689
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0214 - val_accuracy: 0.7468 - val_loss: 2.8038
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0210 - val_accuracy: 0.7078 - val_loss: 2.6571
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0308 - val_accuracy: 0.7143 - val_loss: 2.4334
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0084 - val_accuracy: 0.7468 - val_loss: 2.4100
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.7532 - val_loss: 2.5483
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9821 - loss: 0.0574 - val_accuracy: 0.7013 - val_loss: 2.6775
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0369 - val_accuracy: 0.7208 - val_loss: 2.5411
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 5.3254e-04 - val_accuracy: 0.7208 - val_loss: 2.5750
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 2.8667e-04 - val_accuracy: 0.7273 - val_loss: 2.6185
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.8760e-04 - val_accuracy: 0.7208 - val_loss: 2.7083
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.3760e-04 - val_accuracy: 0.7078 - val_loss: 2.8340
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0903 - val_accuracy: 0.7273 - val_loss: 2.8583
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0051 - val_accuracy: 0.7078 - val_loss: 2.8617
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 3.0189e-04 - val_accuracy: 0.7143 - val_loss: 2.8365
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.3041e-04 - val_accuracy: 0.7143 - val_loss: 2.8443
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 9.5549e-05 - val_accuracy: 0.7078 - val_loss: 2.8939
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 6.9830e-05 - val_accuracy: 0.7078 - val_loss: 2.9983
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 4.7690e-05 - val_accuracy: 0.7078 - val_loss: 3.0333
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 3.8306e-04 - val_accuracy: 0.7013 - val_loss: 3.4982
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9805 - loss: 0.0795 - val_accuracy: 0.7208 - val_loss: 2.9243
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0025 - val_accuracy: 0.7273 - val_loss: 2.8753
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 2.4782e-04 - val_accuracy: 0.7273 - val_loss: 2.9205
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.2020e-04 - val_accuracy: 0.7208 - val_loss: 2.9506
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 9.3486e-05 - val_accuracy: 0.7208 - val_loss: 3.0113
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 6.3648e-05 - val_accuracy: 0.7078 - val_loss: 3.1313
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9902 - loss: 0.0291 - val_accuracy: 0.7273 - val_loss: 3.1032
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0224 - val_accuracy: 0.7208 - val_loss: 2.9709
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0162 - val_accuracy: 0.7468 - val_loss: 2.8266
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0155 - val_accuracy: 0.7143 - val_loss: 2.9412
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0472 - val_accuracy: 0.6948 - val_loss: 2.8875
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 8.6135e-04 - val_accuracy: 0.7078 - val_loss: 2.8694
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0069 - val_accuracy: 0.6883 - val_loss: 2.9158
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0063 - val_accuracy: 0.7338 - val_loss: 2.9960
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0641 - val_accuracy: 0.7273 - val_loss: 2.7412
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0053 - val_accuracy: 0.7273 - val_loss: 2.9043
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0441 - val_accuracy: 0.7208 - val_loss: 2.5500
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 2.2567e-04 - val_accuracy: 0.7208 - val_loss: 2.5762
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.5775e-04 - val_accuracy: 0.7273 - val_loss: 2.6382
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.1181e-04 - val_accuracy: 0.7273 - val_loss: 2.7518
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 7.5374e-05 - val_accuracy: 0.7273 - val_loss: 2.8425
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0018 - val_accuracy: 0.7273 - val_loss: 3.1501
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0164 - val_accuracy: 0.7338 - val_loss: 2.8861
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.7143 - val_loss: 3.0040
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9870 - loss: 0.0511 - val_accuracy: 0.6948 - val_loss: 3.1286
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0084 - val_accuracy: 0.7403 - val_loss: 2.9836
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0034 - val_accuracy: 0.7208 - val_loss: 3.1332
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0474 - val_accuracy: 0.7013 - val_loss: 3.0778
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0175 - val_accuracy: 0.7338 - val_loss: 2.8132
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 4.1946e-04 - val_accuracy: 0.7338 - val_loss: 2.8256
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 9.0869e-05 - val_accuracy: 0.7403 - val_loss: 2.8535
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 7.0409e-05 - val_accuracy: 0.7273 - val_loss: 2.9069
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 5.5393e-05 - val_accuracy: 0.7208 - val_loss: 2.9697
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9902 - loss: 0.0367 - val_accuracy: 0.7273 - val_loss: 2.9255
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0123 - val_accuracy: 0.7208 - val_loss: 2.6881
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.7273 - val_loss: 2.8166
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 9.2695e-05 - val_accuracy: 0.7273 - val_loss: 2.8118
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 6.4442e-05 - val_accuracy: 0.7273 - val_loss: 2.8424
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 4.8406e-05 - val_accuracy: 0.7208 - val_loss: 2.9294
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 3.5190e-05 - val_accuracy: 0.7273 - val_loss: 2.9349
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 2.4300e-05 - val_accuracy: 0.7338 - val_loss: 2.9635
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 1.9084e-05 - val_accuracy: 0.7403 - val_loss: 3.0448
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 1.4880e-05 - val_accuracy: 0.7273 - val_loss: 3.0965
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 1.2416e-05 - val_accuracy: 0.7273 - val_loss: 3.1212
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 1.0409e-05 - val_accuracy: 0.7338 - val_loss: 3.1457
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 8.9186e-06 - val_accuracy: 0.7338 - val_loss: 3.1769
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 7.8683e-06 - val_accuracy: 0.7273 - val_loss: 3.2113
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 7.2280e-06 - val_accuracy: 0.7338 - val_loss: 3.2254
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 6.4531e-06 - val_accuracy: 0.7338 - val_loss: 3.2369
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 5.9853e-06 - val_accuracy: 0.7273 - val_loss: 3.2613
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 5.5082e-06 - val_accuracy: 0.7273 - val_loss: 3.2786
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 5.1361e-06 - val_accuracy: 0.7338 - val_loss: 3.2933
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 4.8418e-06 - val_accuracy: 0.7338 - val_loss: 3.3104
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 4.5444e-06 - val_accuracy: 0.7338 - val_loss: 3.3255
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 4.2731e-06 - val_accuracy: 0.7338 - val_loss: 3.3374
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 4.0451e-06 - val_accuracy: 0.7338 - val_loss: 3.3421
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 3.8504e-06 - val_accuracy: 0.7338 - val_loss: 3.3601
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 3.6590e-06 - val_accuracy: 0.7338 - val_loss: 3.3706
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 3.4865e-06 - val_accuracy: 0.7338 - val_loss: 3.3793
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 3.3514e-06 - val_accuracy: 0.7338 - val_loss: 3.3908
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 3.2057e-06 - val_accuracy: 0.7338 - val_loss: 3.4002
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 3.0962e-06 - val_accuracy: 0.7338 - val_loss: 3.4095
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 2.9635e-06 - val_accuracy: 0.7338 - val_loss: 3.4281
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 2.8549e-06 - val_accuracy: 0.7338 - val_loss: 3.4329
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 2.7574e-06 - val_accuracy: 0.7338 - val_loss: 3.4418
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 2.6804e-06 - val_accuracy: 0.7338 - val_loss: 3.4465
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 2.5582e-06 - val_accuracy: 0.7338 - val_loss: 3.4525
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 2.4695e-06 - val_accuracy: 0.7338 - val_loss: 3.4555
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 2.3860e-06 - val_accuracy: 0.7338 - val_loss: 3.4685
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 2.3147e-06 - val_accuracy: 0.7338 - val_loss: 3.4789
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 2.2508e-06 - val_accuracy: 0.7338 - val_loss: 3.4861
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 2.1801e-06 - val_accuracy: 0.7338 - val_loss: 3.4899
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 2.1122e-06 - val_accuracy: 0.7338 - val_loss: 3.5003
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 2.0547e-06 - val_accuracy: 0.7338 - val_loss: 3.5064
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 2.0024e-06 - val_accuracy: 0.7338 - val_loss: 3.5143
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.9509e-06 - val_accuracy: 0.7338 - val_loss: 3.5214
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.9027e-06 - val_accuracy: 0.7273 - val_loss: 3.5279
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.8553e-06 - val_accuracy: 0.7273 - val_loss: 3.5341
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.8098e-06 - val_accuracy: 0.7273 - val_loss: 3.5408
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.7685e-06 - val_accuracy: 0.7338 - val_loss: 3.5469
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.7279e-06 - val_accuracy: 0.7338 - val_loss: 3.5537
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.6872e-06 - val_accuracy: 0.7273 - val_loss: 3.5589
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.6520e-06 - val_accuracy: 0.7273 - val_loss: 3.5662
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.6208e-06 - val_accuracy: 0.7273 - val_loss: 3.5722
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.5798e-06 - val_accuracy: 0.7273 - val_loss: 3.5782
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.5453e-06 - val_accuracy: 0.7273 - val_loss: 3.5836
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.5095e-06 - val_accuracy: 0.7273 - val_loss: 3.5902
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.4864e-06 - val_accuracy: 0.7273 - val_loss: 3.5932
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.4616e-06 - val_accuracy: 0.7273 - val_loss: 3.5977
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.4291e-06 - val_accuracy: 0.7273 - val_loss: 3.6030
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.3995e-06 - val_accuracy: 0.7208 - val_loss: 3.6096
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.3731e-06 - val_accuracy: 0.7208 - val_loss: 3.6137
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.3466e-06 - val_accuracy: 0.7208 - val_loss: 3.6186
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.3251e-06 - val_accuracy: 0.7208 - val_loss: 3.6232
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.3001e-06 - val_accuracy: 0.7208 - val_loss: 3.6275
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.2803e-06 - val_accuracy: 0.7208 - val_loss: 3.6318
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.2608e-06 - val_accuracy: 0.7208 - val_loss: 3.6349
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.2377e-06 - val_accuracy: 0.7208 - val_loss: 3.6397
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.2172e-06 - val_accuracy: 0.7208 - val_loss: 3.6444
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.1998e-06 - val_accuracy: 0.7208 - val_loss: 3.6505
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.1803e-06 - val_accuracy: 0.7208 - val_loss: 3.6547
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.1622e-06 - val_accuracy: 0.7208 - val_loss: 3.6581
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.1427e-06 - val_accuracy: 0.7208 - val_loss: 3.6606
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.1245e-06 - val_accuracy: 0.7208 - val_loss: 3.6655
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.1110e-06 - val_accuracy: 0.7208 - val_loss: 3.6703
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.0920e-06 - val_accuracy: 0.7208 - val_loss: 3.6776
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.0776e-06 - val_accuracy: 0.7208 - val_loss: 3.6798
Epoch 159/200

In [73]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Trial 3 Complete [00h 00m 04s]
val_accuracy: 0.6428571343421936

Best val_accuracy So Far: 0.7727272510528564
Total elapsed time: 00h 00m 15s

In [ ]:
model =